Repository Real-Dev-Squad/website-www, pull requests merged in 2023-07, with the labels that each got.

#506 HTML tags have been removed from all card descriptions.
  app/constants/cards-data.js
  tests/constants/cards-data.js
Labels: UI, ember-migration

#527 [Ember-Migration] Added `numberOfHours` field in Join form
  app/components/join-steps/step-four.hbs
  app/components/join-steps/step-four.js
  app/components/join-steps/step-three.hbs
  app/components/join-steps/step-three.js
  app/components/stepper.hbs
  tests/integration/components/step-four-test.js
Labels: enhancement, ember-migration

#540 [Ember-Migration] Fixed redirection and updated urls
  app/components/navbar.js
  app/constants/urls.js
  config/environment.js
Labels: ember-migration
