Repository Real-Dev-Squad/website-www, pull requests merged in 2023-01, with the labels that each got.

#350 [Ember-Migration] Handled Sign In/ Sign Up Flow
  app/components/navbar.hbs
  app/components/navbar.js
  app/constants/urls.js
  app/controllers/application.js
  app/helpers/.gitkeep
  app/routes/application.js
  app/services/login.js
  app/styles/navbar.module.css
  app/templates/application.hbs
  package.json
  tests/integration/components/navbar-test.js
  tests/unit/.gitkeep
  tests/unit/services/login-test.js
  yarn.lock
Labels: enhancement, ember-migration, tests

#377 [Ember-Migration] Added a /join route and initial page
  .gitignore
  app/index.html
  app/router.js
  app/routes/join.js
  app/templates/application.hbs
  app/templates/join.hbs
  tests/unit/routes/join-test.js
Labels: ember-migration

#380 [Ember-Migration] Created input (Textfield, Select Dropdown, Textarea) and button components
  app/components/button.hbs
  app/components/dropdown.hbs
  app/components/input-box.hbs
  app/components/text-area-box.hbs
  app/styles/app.css
  app/styles/button.module.css
  app/styles/dropdown.module.css
  app/styles/input.module.css
  app/styles/join.module.css
  app/styles/textarea.module.css
  app/styles/variables.css
  app/templates/join.hbs
  tests/integration/components/button-test.js
  tests/integration/components/dropdown-test.js
  tests/integration/components/input-box-test.js
  tests/integration/components/text-area-box-test.js
Labels: ember-migration

#386 [Ember-Migration] Join Stepper UI
  app/components/button.hbs
  app/components/dropdown.hbs
  app/components/input-box.hbs
  app/components/join-steps/step-five.hbs
  app/components/join-steps/step-five.js
  app/components/join-steps/step-four.hbs
  app/components/join-steps/step-four.js
  app/components/join-steps/step-one.hbs
  app/components/join-steps/step-one.js
  app/components/join-steps/step-three.hbs
  app/components/join-steps/step-three.js
  app/components/join-steps/step-two.hbs
  app/components/join-steps/step-two.js
  app/components/reusables/button.hbs
  app/components/reusables/dropdown.hbs
  app/components/reusables/input-box.hbs
  app/components/reusables/text-area-box.hbs
  app/components/stepper.hbs
  app/components/stepper.js
  app/components/text-area-box.hbs
  app/constants/country-list.js
  app/constants/social-data.js
  app/constants/stepper-data.js
  app/constants/toast-options.js
  app/constants/urls.js
  app/styles/app.css
  app/styles/button.module.css
  app/styles/dropdown.module.css
  app/styles/input.module.css
  app/styles/join.module.css
  app/styles/stepper.module.css
  app/styles/textarea.module.css
  app/styles/variables.css
  app/templates/join.hbs
  package.json
  tests/constants/urls.js
  tests/integration/components/button-test.js
  tests/integration/components/dropdown-test.js
  tests/integration/components/input-box-test.js
  tests/integration/components/step-five-test.js
  tests/integration/components/step-four-test.js
  tests/integration/components/step-one-test.js
  tests/integration/components/step-three-test.js
  tests/integration/components/step-two-test.js
  tests/integration/components/stepper-test.js
  tests/integration/components/text-area-box-test.js
  yarn.lock
Labels: feature task, ember-migration

#388 [Ember-Migration] Docs: Contributing.md
  CONTRIBUTING.md
Labels: documentation, ember-migration

#400 [Ember-Migration] Added Volta
  package.json
Labels: ember-migration
