Repository Real-Dev-Squad/website-www, pull requests merged in 2023-12, with the labels that each got.

#766 [Bug] fastboot error
  app/components/scroll-to-top.js
Labels: ember-branch

#759 Feat/goto page
  app/constants/urls.js
  app/controllers/goto.js
  app/router.js
  app/routes/application.js
  app/routes/goto.js
  app/styles/app.css
  app/styles/goto.module.css
  app/templates/goto.hbs
Labels: ember-migration

#735 Integrate signup api in onboarding
  app/adapters/application.js
  app/adapters/user.js
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-one.js
  app/constants/error-messages.js
  app/models/user.js
  app/serializers/user.js
  app/services/onboarding.js
  tests/integration/components/signup-steps/step-one-test.js
  tests/unit/services/onboarding-test.js
Labels: OnboardingFlow
