Repository Real-Dev-Squad/website-www, pull requests merged in 2023-09, with the labels that each got.

#576 [Live-Site]: Onboarding flow for the users
  app/components/live-join.hbs
  app/components/live-panel.hbs
  app/components/live-roles.hbs
  app/components/live-sidebar.hbs
  app/components/room-code-modal.hbs
  app/components/room-code-modal.js
  app/components/room-code.hbs
  app/components/room-code.js
  app/constants/live.js
  app/controllers/live.js
  app/services/live.js
  app/styles/app.css
  app/styles/kickout-modal.module.css
  app/styles/live-roles.module.css
  app/styles/room-code-modal.module.css
  app/templates/live.hbs
  tests/acceptance/live-test.js
  tests/integration/components/live-panel-test.js
  tests/integration/components/live-roles-test.js
  tests/integration/components/room-code-modal-test.js
  tests/integration/components/room-code-test.js
  tests/unit/routes/live-test.js
Labels: live-site

#588 [Onboarding Flow] Added Page For Archived User
  app/components/onboarding-card.hbs
  app/controllers/join.js
  app/routes/join.js
  app/styles/app.css
  app/styles/intro.module.css
  app/styles/join-section.module.css
  app/styles/onboarding-card.module.css
  app/templates/join.hbs
  tests/integration/components/onboarding-card-test.js
Labels: ember-migration, OnboardingFlow

#626 Feature/sidebar
  app/components/live-participants.hbs
  app/components/live-participants.js
  app/components/live-sidebar.hbs
  app/components/live-sidebar.js
  app/services/live.js
  tests/constants/participants-data.js
  tests/integration/components/live-participants-test.js
  tests/integration/components/live-sidebar-test.js
Labels: live-site

#607 [Onboarding Flow]- Created two input fields, 'firstname' and 'lastname' in signup Details page
  app/components/onboarding-card.hbs
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-one.js
  app/components/signup-steps/step-zero.hbs
  app/components/stepper-signup.hbs
  app/components/stepper-signup.js
  app/controllers/join.js
  app/services/feature-flag.js
  app/styles/dropdown.module.css
  app/styles/input.module.css
  app/styles/onboarding-card.module.css
  app/styles/stepper.module.css
  app/styles/variables.css
  app/templates/join.hbs
  public/assets/icons/link-logo.png
  public/assets/icons/onboarding-card-github-logo.png
  public/assets/icons/onboarding-card-rds-logo.png
  tests/integration/components/signup-steps/step-one-test.js
  tests/integration/components/signup-steps/step-zero-test.js
  tests/integration/components/stepper-signup-test.js
Labels: ember-migration, OnboardingFlow

#616 [Live-Site] - fix to run on local enviroment
  app/constants/urls.js
Labels: live-site

#634 Create login card and github link card
  app/components/signup-steps/step-zero.hbs
  app/components/signup-steps/step-zero.js
  app/components/stepper-signup.hbs
  app/components/stepper-signup.js
  app/controllers/join.js
  app/styles/onboarding-card.module.css
  public/assets/icons/link-logo.png
  public/assets/icons/onboarding-card-github-logo.png
  public/assets/icons/rds-github-link.png
  tests/integration/components/signup-steps/step-zero-test.js
  tests/unit/controllers/join-test.js
Labels: OnboardingFlow

#622 [Onboarding Flow]- Add disabled input field 'username' and 'Generate Username' button in signup Details page
  app/components/reusables/button.hbs
  app/components/reusables/onboarding-input.hbs
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-one.js
  app/components/stepper-signup.hbs
  app/components/stepper-signup.js
  app/styles/button.module.css
  app/styles/input.module.css
  app/styles/onboarding-card.module.css
  app/styles/variables.css
  tests/integration/components/signup-steps/step-one-test.js
Labels: ember-migration, OnboardingFlow

#650 [Live-Site] Refactor/live site stylings
  app/components/live-join.hbs
  app/components/live-participants.hbs
  app/styles/live-header.module.css
  app/styles/live-join.module.css
  app/styles/live-sidebar.module.css
  app/styles/live.module.css
  app/styles/variables.css
  app/templates/live.hbs
Labels: live-site

#646 [Onboarding Flow]- Add role option for a user on signup detail page
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-one.js
  app/components/stepper-signup.js
  app/constants/stepper-signup-data.js
  app/styles/onboarding-card.module.css
  app/styles/stepper.module.css
  tests/integration/components/signup-steps/step-one-test.js
Labels: OnboardingFlow

#659 Getting started page
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-two.hbs
  app/components/signup-steps/step-zero.hbs
  app/components/stepper-signup.hbs
  app/styles/onboarding-card.module.css
  tests/integration/components/signup-steps/step-two-test.js
Labels: OnboardingFlow

#652 [Onboarding Flow]-Signup Process for Different User Roles
  app/components/signup-steps/step-one.hbs
  app/components/signup-steps/step-one.js
  app/components/signup-steps/step-two.hbs
  app/components/signup-steps/step-two.js
  app/components/stepper-signup.hbs
  app/components/stepper-signup.js
  app/styles/onboarding-card.module.css
  tests/integration/components/signup-steps/step-one-test.js
  tests/integration/components/signup-steps/step-two-test.js
Labels: OnboardingFlow

#641 [Live-Site] Feature/loading
  app/components/live-participants.hbs
  app/services/live.js
  app/styles/live-sidebar.module.css
Labels: live-site

#669 [Live-Site] Fix/UI live site
  app/components/live-sidebar.hbs
  app/components/scroll-to-top.hbs
  app/components/scroll-to-top.js
  app/styles/live-header.module.css
  app/styles/live-sidebar.module.css
  app/styles/live.module.css
  app/templates/live.hbs
  public/assets/starting-soon.mp4
  tests/integration/components/live-sidebar-test.js
Labels: live-site

#666 Link join steps in onboarding flow
  app/components/signup-steps/step-two.hbs
  app/components/signup-steps/step-zero.hbs
  app/components/stepper-signup.hbs
  app/components/stepper-signup.js
  app/styles/onboarding-card.module.css
  tests/integration/components/signup-steps/step-two-test.js
  tests/integration/components/signup-steps/step-zero-test.js
Labels: OnboardingFlow

#678 [Live-Site] : Fix/UI bugs
  app/components/live-sidebar.hbs
  app/components/video-screen.hbs
  app/components/video-screen.js
  app/services/live.js
  app/styles/app.css
  app/styles/live-header.module.css
  app/styles/live-sidebar.module.css
  app/styles/live.module.css
  app/styles/video-screen.module.css
  app/templates/live.hbs
  tests/integration/components/live-sidebar-test.js
Labels: live-site
