Repository Real-Dev-Squad/website-www, pull requests merged in 2023-08, with the labels that each got.

#569 [Ember-Migration] Added intro page for super user
  app/components/applicant-intro.hbs
  app/components/applicant-intro.js
  app/components/join-steps/step-five.hbs
  app/components/stepper.hbs
  app/components/unauthorized.hbs
  app/constants/apis.js
  app/controllers/intro.js
  app/router.js
  app/routes/intro.js
  app/services/live.js
  app/styles/app.css
  app/styles/input.module.css
  app/styles/intro.module.css
  app/styles/join-section.module.css
  app/styles/stepper.module.css
  app/templates/intro.hbs
  app/templates/page-not-found.hbs
  config/environment.js
  public/assets/images/errors/401.svg
  public/assets/images/errors/404.svg
  public/assets/images/not-found.png
  tests/acceptance/back-to-home-button-test.js
  tests/acceptance/join-section-button-test.js
  tests/integration/components/applicant-intro-test.js
  tests/integration/components/step-five-test.js
  tests/integration/components/unauthorized-test.js
  tests/unit/controllers/intro-test.js
  tests/unit/routes/intro-test.js
  tests/unit/routes/page-not-found-test.js
Labels: feature task, ember-migration

#564 Fix failing tests
  app/adapters/application.js
  app/constants/apis.js
  app/constants/urls.js
  app/controllers/application.js
  app/services/live.js
  config/environment.js
  tests/acceptance/live-test.js
  tests/constants/urls.js
  tests/integration/components/footer-test.js
  tests/integration/components/more-about-test.js
  tests/integration/components/navbar-test.js
Labels: ember-migration, tests

#556 Remove test on commit
  package.json
Labels: enhancement, ember-migration, deployments

#555 add local-ssl-proxy-for-dev
  package.json
  yarn.lock
Labels: enhancement, DX, ember-migration

#571 Temporarily disable join button to prevent navigation to URL
  css/main.css
  index.html
Labels: good first issue, beginner friendly

#572 [Ember-Migration] Error Messages in Join Section
  app/components/join-steps/step-one.js
  app/components/join-steps/step-three.hbs
  app/components/join-steps/step-three.js
  app/components/join-steps/step-two.hbs
  app/components/join-steps/step-two.js
  app/constants/join.js
  app/styles/join-section.module.css
  app/styles/variables.css
  app/utils/validator.js
  tests/unit/utils/validator-test.js
Labels: enhancement, UI, ember-migration
