Repository Real-Dev-Squad/website-www, pull requests merged in 2025-01, with the labels that each got.

#971 fix/sentence correction
  app/components/join-section.hbs
  app/templates/subscribe.hbs
Labels: documentation, good first issue, beginner friendly, UI, hotfix

#972 refactor(970): moves notices for joining to its own component
  app/components/join-section.hbs
  app/components/notice-for-joining.hbs
  app/controllers/subscribe.js
  app/templates/subscribe.hbs
  tests/integration/components/notice-for-joining-test.js
Labels: enhancement, refactor-only

#968 [My Site Migration] Test Cases for identity linking page
  app/components/identity/blocked.hbs
  app/components/identity/verified.hbs
  app/controllers/identity.js
  app/routes/identity.js
  app/templates/identity.hbs
  tests/integration/components/identity/blocked.js
  tests/integration/components/identity/get-started.js
  tests/integration/components/identity/step1.js
  tests/integration/components/identity/step2.js
  tests/integration/components/identity/step3.js
  tests/integration/components/identity/verified.js
Labels: my-site-migration

#986 (feat) : hbs file for discord page and test cases
  app/styles/app.css
  app/styles/discord.module.css
  app/styles/variables.css
  app/templates/discord.hbs
  app/templates/disocrd.hbs
  public/assets/images/discord-connector.svg
  public/assets/images/discord-logo.png
  tests/acceptance/discord-test.js
Labels: ember-migration
